### ISSUE TITLE
1 - Version 1.0.2 show the Fatal Errors

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-IntelliJ-plugin#13]
https://www.youtube.com/watch?v=7I1-F9sIvyk

![image](https://user-images.githubusercontent.com/23308710/116981871-643ba800-acc8-11eb-8d90-1ef4045c2632.png)

java.lang.StringIndexOutOfBoundsException: offset 481, count -1, length 32768
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.rangeCheck(String.java:280)
	at java.base/java.lang.String.<init>(String.java:276)
	at org.antlr.v4.runtime.ANTLRInputStream.getText(ANTLRInputStream.java:214)
	at org.obp.scalaparsing.FoundMethodsVisitor.retrieveCtxText(FoundMethodsVisitor.java:75)
	at org.obp.scalaparsing.FoundMethodsVisitor.getScalaFunction(FoundMethodsVisitor.java:62)
	at org.obp.scalaparsing.FoundMethodsVisitor.visitFunDef(FoundMethodsVisitor.java:34)
	at org.obp.scalaparsing.FoundMethodsVisitor.visitFunDef(FoundMethodsVisitor.java:19)
	at obp.settings.antlrgenerated.ScalaParser$FunDefContext.accept(ScalaParser.java:7294)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at obp.settings.antlrgenerated.ScalaBaseVisitor.visitDef(ScalaBaseVisitor.java:580)
	at obp.settings.antlrgenerated.ScalaParser$DefContext.accept(ScalaParser.java:7019)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at obp.settings.antlrgenerated.ScalaBaseVisitor.visitBlockStat(ScalaBaseVisitor.java:244)
	at obp.settings.antlrgenerated.ScalaParser$BlockStatContext.accept(ScalaParser.java:3167)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at obp.settings.antlrgenerated.ScalaBaseVisitor.visitBlock(ScalaBaseVisitor.java:237)
	at obp.settings.antlrgenerated.ScalaParser$BlockContext.accept(ScalaParser.java:3072)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.obp.scalaparsing.FoundMethodsVisitor.parseScalaFunction(FoundMethodsVisitor.java:54)
	at org.obp.settings.PopupDialogAction.actionPerformed(PopupDialogAction.java:89)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:265)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:82)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:115)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:198)
	at java.desktop/java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:396)
	at java.desktop/java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:364)
	at java.desktop/java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:375)
	at java.desktop/java.awt.MenuComponent.dispatchEvent(MenuComponent.java:363)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by vladimirkozhaev** [comment]
@hongwei1 Please, add the sourcecode of the mentioned file that you have an error with, or send it directly.

**Comment by vladimirkozhaev** [comment]
I have fixed the fatal error, but problem is that the ANTLR4 Scala grammar that I get on the internet is not perfect.
So, when we try to multi-select code what the given ANTLR grammar can't recognize we have wrong parsing. As result, we have wrong behavior (please see attached picture)

So, we can go forward with two ways
1. Live it as is for now and get back to it when other functionality will work fine
2. Try to improve scala parsing code, for example, we can use IntelliJ functional to parse the code instead of ANTLR. 

I recommend you use scenario 1 as in my humble opinion have not blocked bugs in MVP it's ok, but it up to you to decide

**Comment by vladimirkozhaev** [comment]
![image](https://user-images.githubusercontent.com/1598180/117078369-67737a00-ad42-11eb-96dc-7b36fa0e86bb.png)


> 

>

**Comment by hongwei1** [comment]
scenario 1 --> But lots of methods are not working...

![image](https://user-images.githubusercontent.com/23308710/117108220-294a7a80-ad83-11eb-8832-81491aace328.png)



 scenario 2 --> Try to improve scala parsing code ??? Why do we need to parse the scala code?? Can we just treat as a String?? and rest server will check it anyway..

**Comment by hongwei1** [comment]
![image](https://user-images.githubusercontent.com/23308710/117807085-72a33a00-b25b-11eb-9bc5-b19d4fe39e7b.png)

See the second method body, it is the `=` there...

**Comment by hongwei1** [comment]
![image](https://user-images.githubusercontent.com/23308710/117807230-a1b9ab80-b25b-11eb-95f5-dc95ec99a2c3.png)

**Comment by vladimirkozhaev** [comment]
Problem with the scala code parsing we need to detect where our function start and function ends. It's the obvious question: why we can't just get the string from start to end of the function. Answer is because there are a lot of cases. And this cases exactly what we do with the grammar: describe these cases.

**Comment by hongwei1** [comment]
![image](https://user-images.githubusercontent.com/23308710/117807986-a3d03a00-b25c-11eb-860d-d23392382922.png)

**Comment by vladimirkozhaev** [comment]
So, I need to check do we have "override" keyword and if not just send the string as single selection. If we have override, I need to use token after it as function name
Isn't it?
I just want to describe all cases.


tesobe_hongwei
2:36 PM
ok
